import { v4 as uuidv4 } from 'uuid';


export const Books = [
  {
    "id": "1",
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb_9rN3tWEzpjW3gO-mFOAhcg9Bom29WqXoA&s",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    "pages": 209,
    "title": "Things Fall Apart",
    "category": "Fiction",
    "year": 1958
  },
  {
     "id": "2",
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGV8A6RmwFbKqf1T6lZRe70yE6ccOAwU1-_s2xfjQc9eCXnVvW4UOBeqJFkpobJXoUVNY&usqp=CAU",
    "language": "Danish",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    "pages": 784,
    "title": "Fairy tales",
    "category": "Fantasy & Science Fiction",
    "year": 1836
  },
  {
    "id": "3",
    "author": "Jane Austen",
    "country": "United Kingdom",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq-FUlp1u38BM9s-ouQsDaLNEkqSsBbeSMmrW23L1jmMU2zAs0HwttfLPc8ihfSrnu_wo&usqp=CAU",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    "pages": 226,
    "title": "Pride and Prejudice",
    "category": "Fiction",
    "year": 1813
  },
  {
    "id": "4",
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS65RqIgjkLE4xyv3BawqGtSdUwkccrocw8jxGPElr0ktBJXagU-FBgsuZFZav04CXccso&usqp=CAU",
    "language": "French, English",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    "pages": 256,
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "category": "Fiction",
    "year": 1952
  },
  {
    "id": "5",
    "author": "Giovanni Boccaccio",
    "country": "Italy",
    "imageLink": "https://m.media-amazon.com/images/I/91cpIY0eoyL._UF1000,1000_QL80_.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
    "pages": 1024,
    "title": "The Decameron",
    "category": "Romance",
    "year": 1351
  },
  {
    "id": "6",
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "imageLink": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1200115484i/2235497.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Ficciones\n",
    "pages": 224,
    "title": "Ficciones",
    "category": "Fantasy & Science Fiction",
    "year": 1965
  },
  {
    "id": "7",
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeB2suViddv3Tyb3TfPuvxKR8DCNWGl1b77A&s",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    "pages": 185,
    "title": "The Stranger",
    "category": "Fiction",
    "year": 1942
  },
  {
    "id": "8",
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRh4vHAzEQGN8gFYDKJ8PQizbcesAZLR1SFVgM-PoQGwUJ0shokN8UGHXLXeWKdwT3Wggg&usqp=CAU",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
    "pages": 1056,
    "title": "Don Quijote De La Mancha",
    "category": "Romance",
    "year": 1610
  },
  {
    "id": "9",
    "author": "Geoffrey Chaucer",
    "country": "England",
    "imageLink": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388177331i/32816.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    "pages": 544,
    "title": "The Canterbury Tales",
    "category": "Fiction",
    "year": 1450
  },
  {
    "id": "10",
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "imageLink": "https://techietonics.com/wp-content/uploads/2024/01/Nostromo-JosephConrad-Review-jpg.webp",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nostromo\n",
    "pages": 320,
    "title": "Nostromo",
    "category": "Adventure",
    "year": 1904
  },
  {
    "id": "11",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "https://m.media-amazon.com/images/I/71O2XIytdqL.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    "pages": 551,
    "title": "Crime and Punishment",
    "category": "Crime & Mystery",
    "year": 1866
  },
  {
    "id": "12",
    "author": "Andy Weir",
    "country": "United States",
    "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/The_Martian_%28Weir_novel%29.jpg/220px-The_Martian_%28Weir_novel%29.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Martian_(Weir_novel)",
    "pages": 369,
    "title": "The Martian",
    "category":"Fantasy & Science Fiction",
    "year": 2011
  },
  {
    "id": "13",
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "https://m.media-amazon.com/images/I/71OZJsgZzQL._AC_UF1000,1000_QL80_.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    "pages": 824,
    "title": "The Brothers Karamazov",
    "category": "Crime & Mystery",
    "year": 1880
  },
  {
    "id": "14",
    "author": "Ralph Ellison",
    "country": "United States",
    "imageLink": "https://m.media-amazon.com/images/I/81aUECLG01L._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Invisible_Man\n",
    "pages": 581,
    "title": "Invisible Man",
    "category": "Fantasy & Science Fiction",
    "year": 1952
  },
  {
    "id": "15",
    "author": "Gustave Flaubert",
    "country": "France",
    "imageLink": "https://m.media-amazon.com/images/I/51u+1xJm0xL._AC_UF1000,1000_QL80_.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Madame_Bovary\n",
    "pages": 528,
    "title": "Madame Bovary",
    "category": "Fiction",
    "year": 1857
  },
  {
    "id": "16",
    "author": "Gustave Flaubert",
    "country": "France",
    "imageLink": "https://bulbynorman.files.wordpress.com/2018/08/flaubert_sentimental-ed2-fc-x-700px.jpg?w=252&h=388",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Sentimental_Education\n",
    "pages": 606,
    "title": "Sentimental Education",
    "category": "Fiction",
    "year": 1869
  },
  {
    "id": "17",
    "author": "Johann Wolfgang von Goethe",
    "country": "Saxe-Weimar",
    "imageLink": "https://m.media-amazon.com/images/I/71-qPW0UDgL._AC_UF1000,1000_QL80_.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    "pages": 158,
    "title": "Faust",
    "category":"Comedy & Satire",
    "year": 1832
  },
  {
    "id": "18",
    "author": "Nikolai Gogol",
    "country": "Russia",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYdhsuWYVHtuxlEKkM7g5o3Xh6vrDUcBxnZlimtsAylu-eGVDyo0F0io_reWSPEHqa8JI&usqp=CAU",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Dead_Souls\n",
    "pages": 432,
    "title": "Dead Souls",
    "category":"Comedy & Satire",
    "year": 1842
  },
  {
    "id": "19",
    "author": "Ernest Hemingway",
    "country": "United States",
    "imageLink": "https://m.media-amazon.com/images/I/71RXc0OoEwL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    "pages": 128,
    "title": "The Old Man and the Sea",
    "category":"Adventure",
    "year": 1952
  },
  {
    "id": "20",
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBF23IXJpqHsie8ngEw0SsgCcXvp6p8x-LmBGh66QP4EbYDzrLr88O37gBXE6aejLoRSY&usqp=CAU",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Trial\n",
    "pages": 160,
    "title": "The Trial",
    "category":"Crime & Mystery",
    "year": 1925
  },
  {
    "id": "21",
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6ysWXYoosC4o4G3V_DuXUWgNDf8CjQTP51jnIp8yZCLOHjk3O7A5oQnolByRJGb9RXKs&usqp=CAU",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    "pages": 352,
    "title": "The Castle",
    "category":"Comedy & Satire",
    "year": 1926
  },
  {
    "id": "22",
    "author": "D. H. Lawrence",
    "country": "United Kingdom",
    "imageLink": "https://m.media-amazon.com/images/I/61n0kpd2aEL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
    "pages": 432,
    "title": "Sons and Lovers",
    "category":"Romance",
    "year": 1913
  },
  {
    "id": "23",
    "author": "Herman Melville",
    "country": "United States",
    "imageLink": "https://m.media-amazon.com/images/I/91xNmlf86yL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Moby-Dick\n",
    "pages": 378,
    "title": "Moby Dick",
    "category":"Adventure",
    "year": 1851
  },
  {
    "id": "24",
    "author": "Michel de Montaigne",
    "country": "France",
    "imageLink": "https://m.media-amazon.com/images/I/71iCNKGTIbL._AC_UF1000,1000_QL80_.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    "pages": 404,
    "title": "Essays",
    "category":"Adventure",
    "year": 1595
  },
  {
    "id": "25",
    "author": "Vladimir Nabokov",
    "country": "Russia/United States",
    "imageLink": "https://m.media-amazon.com/images/I/51Oknho43qL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Lolita\n",
    "pages": 317,
    "title": "Lolita",
    "category":"Romance & Drama",
    "year": 1955
  },
  {
    "id": "26",
    "author": "George Orwell",
    "country": "United Kingdom",
    "imageLink": "https://m.media-amazon.com/images/I/61ZewDE3beL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    "pages": 272,
    "title": "Nineteen Eighty-Four",
    "category":"Fantasy & Science Fiction",
    "year": 1949
  },
  {
    "id": "27",
    "author": "Ovid",
    "country": "Roman Empire",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO_hvCu3T6P7VqJfglpk3r1qcjVcWKCnVirkMnRgZXXnCC-69sLO4bDxr_cSevVkwiwYM&usqp=CAU",
    "language": "Classical Latin",
    "link": "https://en.wikipedia.org/wiki/Metamorphoses\n",
    "pages": 576,
    "title": "Metamorphoses",
    "category":"Comedy & Satire",
    "year": 100
  },
  {
    "id": "28",
    "author": "Edgar Allan Poe",
    "country": "United States",
    "imageLink": "https://m.media-amazon.com/images/I/81c5+NWldwL._UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
    "pages": 842,
    "title": "Tales",
    "category":"Crime & Mystery",
    "year": 1950
  },
  {
    "id": "29",
    "author": "Marcel Proust",
    "country": "France",
    "imageLink": "https://m.media-amazon.com/images/I/817hc-bhanL._UF1000,1000_QL80_.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    "pages": 2408,
    "title": "In Search of Lost Time",
    "category":"Fiction",
    "year": 1920
  },
  {
    "id": "30",
    "author": "Salman Rushdie",
    "country": "United Kingdom, India",
    "imageLink": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1673724335i/14836.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
    "pages": 536,
    "title": "Midnight's Children",
    "category":"Fiction",
    "year": 1981
  },
  {
    "id": "31",
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtPQ2_HrK8QXFg8p1aJLrleQ77aBV4zomihOQPvHuLRu-DYXdIpu0aGYUv-OcxliGYlJg&usqp=CAU",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Hamlet\n",
    "pages": 432,
    "title": "Hamlet",
    "category":"Crime & Mystery",
    "year": 1603
  },
  {
    "id": "32",
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQF5n3B6eQCpRACzhUKGNLxdJEpkdIBpunNBYgTgRpSIfE-uIn-JscgamGAGrk7_LlmzJ8&usqp=CAU",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/King_Lear\n",
    "pages": 384,
    "title": "King Lear",
    "category":"Crime & Mystery",
    "year": 1608
  },
  {
    "id": "33",
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ40OqFfXm71tO1dGzYpYJEz5hlclEIm_0vwlWGckhsIG_-N55-sGf8xnzAxDEmHk5D4B4&usqp=CAU",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Othello\n",
    "pages": 314,
    "title": "Othello",
    "category":"Crime & Mystery",
    "year": 1609
  },
  {
    "id": "34",
    "author": "Sophocles",
    "country": "Greece",
    "imageLink": "https://m.media-amazon.com/images/I/51jOakNjV-L._AC_UF1000,1000_QL80_.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
    "pages": 88,
    "title": "Oedipus the King",
    "category":"Crime & Mystery",
    "year": -430
  },
  {
    "id": "35",
    "author": "Stendhal",
    "country": "France",
    "imageLink": "https://m.media-amazon.com/images/I/61miJdWR1-L._AC_UF1000,1000_QL80_.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
    "pages": 576,
    "title": "The Red and the Black",
    "category":"Crime & Mystery",
    "year": 1830
  },
  {
    "id": "36",
    "author": "Laurence Sterne",
    "country": "England",
    "imageLink": "https://m.media-amazon.com/images/I/81EZjRSfQaL._UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
    "pages": 640,
    "title": "The Life And Opinions of Tristram Shandy",
    "category":"Comedy & Satire",
    "year": 1760
  },
  {
    "id": "37",
    "author": "Italo Svevo",
    "country": "Italy",
    "imageLink": "https://m.media-amazon.com/images/I/51SnOctZrDL._AC_UF1000,1000_QL80_.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    "pages": 412,
    "title": "Confessions of Zeno",
    "category":"Crime & Mystery",
    "year": 1923
  },
  {
    "id": "38",
    "author": "Jonathan Swift",
    "country": "Ireland",
    "imageLink": "https://m.media-amazon.com/images/I/81BzA3z+N9L._UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
    "pages": 178,
    "title": "Gulliver's Travels",
    "category":"Adventure",
    "year": 1726
  },
  {
    "id": "39",
    "author": "Leo Tolstoy",
    "country": "Russia",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCxsluj1NDJSeSvqHFsox8LU_jazl2LEStfuptZ258IGY8Fe8P504Sk8vWOgP45vU1rq0&usqp=CAU",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    "pages": 864,
    "title": "Anna Karenina",
    "category":"Romance & Drama",
    "year": 1877
  },
  {
    "id": "40",
    "author": "Mark Twain",
    "country": "United States",
    "imageLink": "https://m.media-amazon.com/images/I/91sBZnKzEfL._AC_UF1000,1000_QL80_.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
    "pages": 224,
    "title": "The Adventures of Huckleberry Finn",
    "category":"Adventure",
    "year": 1884
  },
  {
    "id": "41",
    "author": "Valmiki",
    "country": "India",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUVUdzb1rdqOs0mOvVqLTGNqQLmWcqahGh9kwZEIqe6kBuX_H0uY92GUz1S5ncU9wkgRY&usqp=CAU",
    "language": "Sanskrit",
    "link": "https://en.wikipedia.org/wiki/Ramayana\n",
    "pages": 152,
    "title": "Ramayana",
    "category":"Adventure",
    "year": -450
  },
  {
    "id": "42",
    "author": "Virgil",
    "country": "Roman Empire",
    "imageLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiayNJA3B5nXIgyVta-9gx6cIe4wRWWB4_zLwy5t2KjiAufZfn_ae5BeyUWo3mtaRKMYg&usqp=CAU",
    "language": "Classical Latin",
    "link": "https://en.wikipedia.org/wiki/Aeneid\n",
    "pages": 442,
    "title": "The Aeneid",
    "category":"Fantasy & Science Fiction",
    "year": -23
  },
  {
    "id": "43",
    "author": "Frank Herbert",
    "country": "United States",
    "imageLink": "https://upload.wikimedia.org/wikipedia/en/thumb/d/de/Dune-Frank_Herbert_%281965%29_First_edition.jpg/220px-Dune-Frank_Herbert_%281965%29_First_edition.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Dune_(novel)",
    "pages": 412,
    "title": "Dune",
    "category":"Fantasy & Science Fiction",
    "year": 1965
  }
]


export const categories = [
  {
    "id": uuidv4(),
    "category_img":"https://www.turito.com/_next/image?url=https%3A%2F%2Fwww.turito.com%2Flearn-internal%2Fwp-content%2Fuploads%2F2023%2F07%2FFiction.png&w=1920&q=50",
    "title":"Fiction"
  },
  {
    "id": uuidv4(),
    "category_img":"https://t3.ftcdn.net/jpg/00/84/65/46/360_F_84654602_scalmAzwCeHp2OxCIYPPaQqhictO4Xsm.jpg",
    "title":"Comedy & Satire"
  },
  {
    "id": uuidv4(),
    "category_img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLTPBH3okMGXMsUFVBVqcO_SVYOZ6a49dlStoMjR2Fty8RBs8KYNMLgU-ETRhTU22hIBs&usqp=CAU",
    "title":"Fantasy & Science Fiction"
  },
  {
    "id": uuidv4(),
    "category_img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi_OYsbfo60Erg_4_SU95uFLOSn29Xsr3Arg&s",
    "title":"Romance & Drama"
  },
  {
    "id": uuidv4(),
    "category_img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxP074_OcnEVJfpgD9usPPE3W1hOyHvxXzsg&s",
    "title": "Crime & Mystery"
  },
  {
    "id": uuidv4(),
    "category_img":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeclBZk2U-hSvLhiZnIu2nH-jpGAvdAk0pyA&s",
    "title" : "Adventure"
  }
]